# Tarefa #

In [1]:
import numpy as np

# A) # 

Verifique se este sistema satisfaz as condições para utilização dos métodos de Decomposicão LU e Cholesky, explicando sua resposta
- LU: menores principais $ \ne 0 $
- Cholesky: simétrica ($ A = A^T$) e positiva definida (menores principais $ > 0 $)

$ det(A_{1}) = \{ 16 \} = 16 > 0$

$ det(A_{2}) = \{16, 4\} \{4,  10\} = 144 > 0$

$ det(A_{3}) = \{16, 4, 8\} \{4, 10, 8\} \{8, 8, 12 \} = 576 > 0$

portanto, todos menores principais são maiores que zero (e também diferentes de zero)

In [11]:
A = np.array([
    [16, 4, 8, 4],
    [4, 10, 8, 4],
    [8, 8, 12, 10],
    [4, 4, 10, 12]
])

if np.allclose(A, A.T):
    print("É simétrica")
else:
    print("Não é simétrica")

É simétrica


A matriz A é simétrica e também satisfaz as condições dos menores principais.

Portanto, podemos usar Gauss, LU e Cholesky.

# B) # 

Gauss

In [4]:
A = np.array([
    [16., 4, 8, 4],
    [4, 10, 8, 4],
    [8, 8, 12, 10],
    [4, 4, 10, 12]
])

b = np.array([
    [32.],
    [26],
    [38],
    [30]
])
n = A.shape[0]

# junta B em A
A = np.hstack((A, b))

for k in range(0, n):

    for i in range(k+1, n): # pega o valor para zerar
        m = A[i,k] / A[k,k]
        
        for j in range (k, n+1): # zera
            A[i,j] = A[i,j] - m * A[k,j]

        b[i] = b[i] - m * b[k]


A = A[:, :n]



x = np.linalg.inv(A) @ b

print(x)

[[1.]
 [1.]
 [1.]
 [1.]]


LU

In [5]:
A = np.array([
    [16., 4, 8, 4],
    [4, 10, 8, 4],
    [8, 8, 12, 10],
    [4, 4, 10, 12]
])

b = np.array([
    [32.],
    [26],
    [38],
    [30]
])

L = np.eye(n)
U = np.zeros((n,n))

for i in range(0, n):
    for j in range(i, n):
        
        soma = 0
        
        for k in range(0 , i):
            soma = soma + L[i,k] * U[k,j]
        
        U[i,j] = A[i,j] - soma


    for j in range(i+1, n):
        
        soma = 0
        
        for k in range(0, i):
            soma = soma + L[j,k] * U[k,i]

        L[j,i] = (A[j,i] - soma) / U[i,i]





y = np.linalg.inv(L) @ b
x = np.linalg.inv(U) @ y

print(x)

[[1.]
 [1.]
 [1.]
 [1.]]


Cholesky

In [6]:
A = np.array([
    [16., 4, 8, 4],
    [4, 10, 8, 4],
    [8, 8, 12, 10],
    [4, 4, 10, 12]
])

b = np.array([
    [32.],
    [26],
    [38],
    [30]
])

G = np.zeros((n,n))

for i in range(0, n):
    for j in range (0, i + 1):
        if i == j:
            soma = 0

            for k in range (0, j):
                soma = soma + G[i,k]**2

            G[i,j] = np.sqrt(A[i,j] - soma)

        else:
            soma = 0
            
            for k in range(0, j):
                soma = soma + G[i,k] * G[j,k]
            
            G[i,j] = (A[i,j] - soma) / G[j,j]


y = np.linalg.inv(G) @ b
x = np.linalg.inv(G.T) @ y

print(x)

[[1.]
 [1.]
 [1.]
 [1.]]


# C) #

In [8]:
print(f"L: \n{L}")
print(f"\nU: \n{U}")

L: 
[[1.         0.         0.         0.        ]
 [0.25       1.         0.         0.        ]
 [0.5        0.66666667 1.         0.        ]
 [0.25       0.33333333 1.5        1.        ]]

U: 
[[16.  4.  8.  4.]
 [ 0.  9.  6.  3.]
 [ 0.  0.  4.  6.]
 [ 0.  0.  0.  1.]]


# D) #

In [10]:
print(f"G: \n{G}")

G: 
[[4. 0. 0. 0.]
 [1. 3. 0. 0.]
 [2. 2. 2. 0.]
 [1. 1. 3. 1.]]
