# Tarefa

In [159]:
import numpy as np

A = np.array([
    [15., 5, -5],
    [4, 10, 1],
    [2, -2, 8]
])

b = np.array([30., 23, -10])

## Jacobi-Richardson ##

In [160]:



itMax = 30
e = 10 ** (-5)
n = A.shape[0]
x = np.array([0.7, -1.6, 0.6])

L = np.zeros((n,n))
D = np.zeros((n,n))
U = np.zeros((n,n))

# construindo L, D e U
for i in range(0, n):
    for j in range(0, n):
        if i > j:
            # elementos abaixo da diagonal
            L[i,j] = A[i,j]

        elif i == j:
            # elementos da diagonal
            D[i,j] = A[i,j]

        elif i < j:
            # elementos acima da diagonal
            U[i,j] = A[i,j]



# algoritmo
k = 0
while True:
    x_novo = (np.linalg.inv(D)) @ (b - (L + U) @ x)

    Erro_absoluto = np.linalg.norm(x_novo - x)

    x = x_novo

    k += 1

    if Erro_absoluto < e:
        break
    elif k == itMax:
        break




print(f"X: \n{x}")
print(f"Iterações: {k}")

Jacobi = ['Jacobi', x, k]


X: 
[ 1.00000083  2.00000076 -1.00000034]
Iterações: 15


## Gauss-Seidel

In [161]:
itMax = 30
e = 10 ** (-5)
n = A.shape[0]
x = np.array([0., 0, 0])

L_estrela = np.zeros((n,n))
U_estrela = np.zeros((n,n))
I = np.eye((n))
B_estrela = b.copy()

# Construindo Le e Ue 
for i in range(0, n):
    for j in range(0, n):
        if i > j:
            # elementos abaixo da diagonal / elemento da diagonal (pivô)
            L_estrela[i,j] = A[i,j] / A[i,i]

            # elementos acima da diagonal / elemento da diagonal (pivô)
        elif i < j:
            U_estrela[i,j] = A[i,j] / A[i,i]

# Construindo Be
for i in range (0, n):
    B_estrela[i] = b[i] / A[i,i]


# algoritmo
k = 0
while True:
    x_novo = -(np.linalg.inv(L_estrela + I)) @ U_estrela @ x + np.linalg.inv(L_estrela + I) @ B_estrela

    Erro_absoluto = np.linalg.norm(x - x_novo)

    x = x_novo

    k += 1

    if k == itMax:
        break
    
    elif Erro_absoluto < e:
        break


print(f"Iterações: \n{k}")
print(f"X: \n{x}")

Gauss = ['Gauss', x, k]




Iterações: 
7
X: 
[ 0.99999936  2.00000025 -0.99999978]


## SOR com w = 1

In [162]:
itMax = 30
e = 10 ** (-5)
n = A.shape[0]
x = np.array([0., 0, 0])

L_estrela = np.zeros((n,n))
U_estrela = np.zeros((n,n))
I = np.eye((n))

xSOR =  np.zeros(n)
x_novoSOR =  np.zeros(n)
xGS = np.zeros(n)
omega = 1.00

# Construindo Le e Ue 
for i in range(0, n):
    for j in range(0, n):
        if i > j:
            # elementos abaixo da diagonal / elemento da diagonal (pivô)
            L_estrela[i,j] = A[i,j] / A[i,i]

            # elementos acima da diagonal / elemento da diagonal (pivô)
        elif i < j:
            U_estrela[i,j] = A[i,j] / A[i,i]

# Construindo Be
for i in range (0, n):
    B_estrela[i] = b[i] / A[i,i]

A_estrela = L_estrela + U_estrela + I

# algoritmo
k = 0
while True:
    
    for i in range(n):
        soma1 = 0
        for j in range(i):
            soma1 += A_estrela[i,j] * x_novoSOR[j]

        soma2 = 0
        for j in range(i+1, n):
            soma2 += A_estrela[i,j] * xSOR[j]

        x_novoSOR[i] = (1 - omega) * xSOR[i] + omega * (B_estrela[i] - soma1 - soma2)

    Erro_absoluto = np.linalg.norm(x_novoSOR - xSOR)

    xSOR = x_novoSOR.copy()
    k += 1

    if Erro_absoluto < e:
        break
    elif k == itMax:
        break


print(f"Iterações: {k}")
print(f"X: \n{xSOR}")

sor1 = ['SOR w = 1', xSOR, k]



Iterações: 7
X: 
[ 0.99999936  2.00000025 -0.99999978]


## SOR com w = 1.5

In [163]:
itMax = 30
e = 10 ** (-5)
n = A.shape[0]
x = np.array([0., 0, 0])

L_estrela = np.zeros((n,n))
U_estrela = np.zeros((n,n))
I = np.eye((n))

xSOR =  np.zeros(n)
x_novoSOR =  np.zeros(n)
xGS = np.zeros(n)
omega = 1.5

# Construindo Le e Ue 
for i in range(0, n):
    for j in range(0, n):
        if i > j:
            # elementos abaixo da diagonal / elemento da diagonal (pivô)
            L_estrela[i,j] = A[i,j] / A[i,i]

            # elementos acima da diagonal / elemento da diagonal (pivô)
        elif i < j:
            U_estrela[i,j] = A[i,j] / A[i,i]

# Construindo Be
for i in range (0, n):
    B_estrela[i] = b[i] / A[i,i]

A_estrela = L_estrela + U_estrela + I

# algoritmo
k = 0
while True:
    
    for i in range(n):
        soma1 = 0
        for j in range(i):
            soma1 += A_estrela[i,j] * x_novoSOR[j]

        soma2 = 0
        for j in range(i+1, n):
            soma2 += A_estrela[i,j] * xSOR[j]

        x_novoSOR[i] = (1 - omega) * xSOR[i] + omega * (B_estrela[i] - soma1 - soma2)

    Erro_absoluto = np.linalg.norm(x_novoSOR - xSOR)

    xSOR = x_novoSOR.copy()
    k += 1

    if Erro_absoluto < e:
        break
    elif k == itMax:
        break


print(f"Iterações: {k}")
print(f"X: \n{xSOR}")

sor15 = ['SOR w = 1.5', xSOR, k]



Iterações: 30
X: 
[ 0.99480566  2.01647277 -0.97997928]


In [164]:
display("Método, array[x1, x2, x2], número de iterações")
display(Jacobi)
display(Gauss)
display(sor1)
display(sor15)

'Método, array[x1, x2, x2], número de iterações'

['Jacobi', array([ 1.00000083,  2.00000076, -1.00000034]), 15]

['Gauss', array([ 0.99999936,  2.00000025, -0.99999978]), 7]

['SOR w = 1', array([ 0.99999936,  2.00000025, -0.99999978]), 7]

['SOR w = 1.5', array([ 0.99480566,  2.01647277, -0.97997928]), 30]