# Métodos Diretos de Sistemas Lineares # 

# Eliminação de Gauss

In [46]:
import numpy as np

In [47]:
A = np.array([[6.,2,-1],
             [2,4,1],
             [3,2,8]])

b = np.array([[7.],
              [7],
              [13]])
n = A.shape[0]

# junta B em A
A = np.hstack((A, b))

for k in range(0, n):

    for i in range(k+1, n): # pega o valor para zerar
        m = A[i,k] / A[k,k]
        
        for j in range (k, n+1): # zera
            A[i,j] = A[i,j] - m * A[k,j]

        b[i] = b[i] - m * b[k]


A = A[:, :n]

print(A)
print(b)

x = np.linalg.inv(A) @ b

print(x)

[[ 6.          2.         -1.        ]
 [ 0.          3.33333333  1.33333333]
 [ 0.          0.          8.1       ]]
[[7.        ]
 [4.66666667]
 [8.1       ]]
[[1.]
 [1.]
 [1.]]


# Decomposição LU

In [65]:
A = np.array([[5.,2,1],
             [3,1,4],
             [1,1,3]])

b = np.array([0., -7, -5])

n = A.shape[0]

L = np.eye(n)
U = np.zeros((n,n))

for i in range(0, n):
    for j in range(i, n):
        
        soma = 0
        
        for k in range(0 , i):
            soma = soma + L[i,k] * U[k,j]
        
        U[i,j] = A[i,j] - soma


    for j in range(i+1, n):
        
        soma = 0
        
        for k in range(0, i):
            soma = soma + L[j,k] * U[k,i]

        L[j,i] = (A[j,i] - soma) / U[i,i]


print(A)
print(L)
print(U)


y = np.linalg.inv(L) @ b
x = np.linalg.inv(U) @ y

print(x)


[[5. 2. 1.]
 [3. 1. 4.]
 [1. 1. 3.]]
[[ 1.   0.   0. ]
 [ 0.6  1.   0. ]
 [ 0.2 -3.   1. ]]
[[ 5.   2.   1. ]
 [ 0.  -0.2  3.4]
 [ 0.   0.  13. ]]
[ 2.49373172e-15  1.00000000e+00 -2.00000000e+00]


# Decomposição Cholesky 

In [85]:
A = np.array([[4.,2,-4],
             [2,10,4],
             [-4,4,9]])

b = np.array([0., 6, 5])

n = A.shape[0]

G = np.zeros((n,n))

for i in range(0, n):
    for j in range (0, i + 1):
        if i == j:
            soma = 0

            for k in range (0, j):
                soma = soma + G[i,k]**2

            G[i,j] = np.sqrt(A[i,j] - soma)

        else:
            soma = 0
            
            for k in range(0, j):
                soma = soma + G[i,k] * G[j,k]
            
            G[i,j] = (A[i,j] - soma) / G[j,j]

print(A)
print(G)

y = np.linalg.inv(G) @ b
x = np.linalg.inv(G.T) @ y

print(x)

[[ 4.  2. -4.]
 [ 2. 10.  4.]
 [-4.  4.  9.]]
[[ 2.  0.  0.]
 [ 1.  3.  0.]
 [-2.  2.  1.]]
[1. 0. 1.]
