# Atividade #

In [8]:
import numpy as np

In [9]:
A = np.array([
    [4., 12, -16],
    [12, 37, -43],
    [-16, -43, 98]
])

b = np.array([
    [1],
    [2],
    [3]
])

n = A.shape[0]

In [10]:
print(np.linalg.det(A))

35.999999999999936


Verificando condições para LU e Gauss -> menores principais != 0

$ A_{1} = (4) $ -> $det(A_{1}) = 4 \ne 0$

$ A_{2} = (4, 12) (12, 37) $ -> $det(A_{2}) = 4 \ne 0 $

$ det(A) = 36 \ne 0 $

Verifcando condições para Cholesky
- $ A = A^T $
- Positiva definida (menores principais > 0)

In [11]:
if np.allclose(A, A.T):
    print("Simétrica")
else:
    print("Não é Simétrica")

Simétrica


Como já visto anteriormente
- $ det(A_{1}) = 4 > 0 $
- $ det(A_{2}) = 4 > 0 $
- $ det(A) = 36 > 0 $

Portanto, é possível usar Gauss, LU e Cholesky

# Gauss #

In [12]:
A = np.array([
    [4., 12, -16],
    [12, 37, -43],
    [-16, -43, 98]
])

b = np.array([
    [1],
    [2],
    [3]
])

# junta B em A
A = np.hstack((A, b))

for k in range(0, n):

    for i in range(k+1, n): # pega o valor para zerar
        m = A[i,k] / A[k,k]
        
        for j in range (k, n+1): # zera
            A[i,j] = A[i,j] - m * A[k,j]

        b[i] = b[i] - m * b[k]


A = A[:, :n]



x = np.linalg.inv(A) @ b

print(x)

[[28.58333333]
 [-7.66666667]
 [ 1.33333333]]


# LU

In [13]:
A = np.array([
    [4., 12, -16],
    [12, 37, -43],
    [-16, -43, 98]
])

b = np.array([
    [1],
    [2],
    [3]
])

L = np.eye(n)
U = np.zeros((n,n))

for i in range(0, n):
    for j in range(i, n):
        
        soma = 0
        
        for k in range(0 , i):
            soma = soma + L[i,k] * U[k,j]
        
        U[i,j] = A[i,j] - soma


    for j in range(i+1, n):
        
        soma = 0
        
        for k in range(0, i):
            soma = soma + L[j,k] * U[k,i]

        L[j,i] = (A[j,i] - soma) / U[i,i]





y = np.linalg.inv(L) @ b
x = np.linalg.inv(U) @ y

print(x)

[[28.58333333]
 [-7.66666667]
 [ 1.33333333]]


# Cholesky

In [14]:
A = np.array([
    [4., 12, -16],
    [12, 37, -43],
    [-16, -43, 98]
])

b = np.array([
    [1],
    [2],
    [3]
])

G = np.zeros((n,n))

for i in range(0, n):
    for j in range (0, i + 1):
        if i == j:
            soma = 0

            for k in range (0, j):
                soma = soma + G[i,k]**2

            G[i,j] = np.sqrt(A[i,j] - soma)

        else:
            soma = 0
            
            for k in range(0, j):
                soma = soma + G[i,k] * G[j,k]
            
            G[i,j] = (A[i,j] - soma) / G[j,j]


y = np.linalg.inv(G) @ b
x = np.linalg.inv(G.T) @ y

print(x)

[[28.58333333]
 [-7.66666667]
 [ 1.33333333]]
