# Métodos Iterativos para Sistemas Lineares

In [1]:
import numpy as np

# Jacobi-Richardson

In [2]:
A = np.array([
    [10., 2, 1],
    [1, 5, 1],
    [2, 3, 10]
])
b = np.array([7., -8, 6])

itMax = 30
e = 10 ** (-2)
n = A.shape[0]
x = np.array([0.7, -1.6, 0.6])

L = np.zeros((n,n))
D = np.zeros((n,n))
U = np.zeros((n,n))

# construindo L, D e U
for i in range(0, n):
    for j in range(0, n):
        if i > j:
            # elementos abaixo da diagonal
            L[i,j] = A[i,j]

        elif i == j:
            # elementos da diagonal
            D[i,j] = A[i,j]

        elif i < j:
            # elementos acima da diagonal
            U[i,j] = A[i,j]

print(f"L: \n{L}")
print(f"D: \n{D}")
print(f"U: \n{U}")



# algoritmo
k = 0
while True:
    x_novo = (np.linalg.inv(D)) @ (b - (L + U) @ x)

    Erro_absoluto = np.linalg.norm(x_novo - x)

    x = x_novo

    k += 1

    if Erro_absoluto < e:
        break
    elif k == itMax:
        break




print(f"X: \n{x}")
print(f"Iterações: {k}")



L: 
[[0. 0. 0.]
 [1. 0. 0.]
 [2. 3. 0.]]
D: 
[[10.  0.  0.]
 [ 0.  5.  0.]
 [ 0.  0. 10.]]
U: 
[[0. 2. 1.]
 [0. 0. 1.]
 [0. 0. 0.]]
X: 
[ 1.000236 -1.998936  1.000284]
Iterações: 5


# Gauss-Seidel

In [3]:
A = np.array([
    [5., 1, 1],
    [3, 4, 1],
    [3, 3, 6]
])

b = np.array([5., 6, 0])

itMax = 30
e = 10 ** (-2)
n = A.shape[0]
x = np.array([0., 0, 0])

L_estrela = np.zeros((n,n))
U_estrela = np.zeros((n,n))
I = np.eye((n))
B_estrela = b

# Construindo Le e Ue 
for i in range(0, n):
    for j in range(0, n):
        if i > j:
            # elementos abaixo da diagonal / elemento da diagonal (pivô)
            L_estrela[i,j] = A[i,j] / A[i,i]

            # elementos acima da diagonal / elemento da diagonal (pivô)
        elif i < j:
            U_estrela[i,j] = A[i,j] / A[i,i]

# Construindo Be
for i in range (0, n):
    B_estrela[i] = b[i] / A[i,i]


# algoritmo
k = 0
while True:
    x_novo = -(np.linalg.inv(L_estrela + I)) @ U_estrela @ x + np.linalg.inv(L_estrela + I) @ B_estrela

    Erro_absoluto = np.linalg.norm(x - x_novo)

    x = x_novo

    k += 1

    if k == itMax:
        break
    
    elif Erro_absoluto < e:
        break


print(f"L Estrela: \n{L_estrela}")
print(f"U Estrela: \n{U_estrela}")
print(f"B Estrela: \n{B_estrela}")
print(f"Iterações: \n{k}")
print(f"X: \n{x}")





L Estrela: 
[[0.   0.   0.  ]
 [0.75 0.   0.  ]
 [0.5  0.5  0.  ]]
U Estrela: 
[[0.   0.2  0.2 ]
 [0.   0.   0.25]
 [0.   0.   0.  ]]
B Estrela: 
[1.  1.5 0. ]
Iterações: 
4
X: 
[ 1.001625  0.998625 -1.000125]


# SOR

In [4]:
A = np.array([
    [5., 1, 1],
    [3, 4, 1],
    [3, 3, 6]
])

b = np.array([5., 6, 0])

itMax = 10
e = 10 ** (-2)
n = A.shape[0]
x = np.array([0., 0, 0])

L_estrela = np.zeros((n,n))
U_estrela = np.zeros((n,n))
I = np.eye((n))

xSOR =  np.zeros(n)
x_novoSOR =  np.zeros(n)
xGS = np.zeros(n)
omega = 1.05

# Construindo Le e Ue 
for i in range(0, n):
    for j in range(0, n):
        if i > j:
            # elementos abaixo da diagonal / elemento da diagonal (pivô)
            L_estrela[i,j] = A[i,j] / A[i,i]

            # elementos acima da diagonal / elemento da diagonal (pivô)
        elif i < j:
            U_estrela[i,j] = A[i,j] / A[i,i]

# Construindo Be
for i in range (0, n):
    B_estrela[i] = b[i] / A[i,i]

A_estrela = L_estrela + U_estrela + I

# algoritmo
k = 0
while True:
    for i in range(n):
        soma1 = 0
        for j in range(i):
            soma1 += A_estrela[i,j] * x_novoSOR[j]

        soma2 = 0
        for j in range(i+1, n):
            soma2 += A_estrela[i,j] * xSOR[j]

        x_novoSOR[i] = (1 - omega) * xSOR[i] + omega * (B_estrela[i] - soma1 - soma2)

    Erro_absoluto = np.linalg.norm(x_novoSOR - xSOR)

    xSOR = x_novoSOR.copy()
    k += 1

    if Erro_absoluto < e:
        break
    elif k == itMax:
        break

print(f"A Estrela: \n{A_estrela}")
print(f"L Estrela: \n{L_estrela}")
print(f"U Estrela: \n{U_estrela}")
print(f"B Estrela: \n{B_estrela}")
print(f"Iterações: {k}")
print(f"X: \n{xSOR}")




A Estrela: 
[[1.   0.2  0.2 ]
 [0.75 1.   0.25]
 [0.5  0.5  1.  ]]
L Estrela: 
[[0.   0.   0.  ]
 [0.75 0.   0.  ]
 [0.5  0.5  0.  ]]
U Estrela: 
[[0.   0.2  0.2 ]
 [0.   0.   0.25]
 [0.   0.   0.  ]]
B Estrela: 
[1.  1.5 0. ]
Iterações: 4
X: 
[ 1.00047253  1.0002533  -1.00027763]
